# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09cebf869a9c07f4b165c898a74cfd02da94feb0753e1c89d0a18493ff4b61dc03db4afede0e125c4a26f35fd129d7e1c0c2a8116d5b17621c1ced352d4fb495

test:
  secret_key_base: 814d19e3c34968ef65db82a245094779e792e0c41d597901d932385d6afe4926e39b854711738b0c26108d9f80d7892ec3fd4bb3706fcd9d687f08ee9835b256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
